In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arrNumPy = np.array(lista)
arrNumPy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arrNumPy)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arrNumPy[1]

2

In [7]:
arrNumPy[0] + arrNumPy[5]

7

In [8]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matriz[0,2] #esto significa [filas,columnas]

3

In [10]:
arrNumPy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arrNumPy[0:5]#slicing, no toma en cuenta el limit o sea la posicion 5 del index en este caso (numero 6)

array([1, 2, 3, 4, 5])

In [12]:
arrNumPy[1:6]

array([2, 3, 4, 5, 6])

In [13]:
arrNumPy[:7] #puedo trabajar sin start

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
arrNumPy[2:] #puedo trabajar sin end

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
arrNumPy[::3] #de tres en tres

array([1, 4, 7])

In [16]:
arrNumPy[-1] #obtiene el ultimo indice de la lista (en reversa)

9

In [17]:
arrNumPy[-3:] #va en reversa a los tres ultimos indices de la lista

array([7, 8, 9])

In [18]:
arrNumPy[::-1] #invierte el orden de la lista

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [21]:
matriz3d = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
matriz3d

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [22]:
matriz3d[0:1] 

array([[[ 2, 17],
        [45, 78]]])

In [23]:
matriz3d[0:1,0:1]

array([[[ 2, 17]]])

In [24]:
matriz3d[0:1,0:1,0:1]

array([[[2]]])

In [25]:
matriz3d

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [26]:
matriz3d[::-1,:,:] #voltea el orden de los arrays exteriores

array([[[76, 33],
        [20, 18]],

       [[88, 92],
        [60, 76]],

       [[ 2, 17],
        [45, 78]]])

In [27]:
matriz3d[:,::-1,:] #Voltea el orden de los arrays interiores

array([[[45, 78],
        [ 2, 17]],

       [[60, 76],
        [88, 92]],

       [[20, 18],
        [76, 33]]])

In [28]:
matriz3d[:,:,::-1] #Voltea el orden de los numeros dentro de los arrays

array([[[17,  2],
        [78, 45]],

       [[92, 88],
        [76, 60]],

       [[33, 76],
        [18, 20]]])

In [29]:
matriz3d[::-1,::-1,::-1]

array([[[18, 20],
        [33, 76]],

       [[76, 60],
        [92, 88]],

       [[78, 45],
        [17,  2]]])