In [1]:
import numpy as np

*Creando el array especificando el argumento dtype= 'float64'*

In [2]:
arr1 = np.array([1,2,3,4],dtype='float64')

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr1

array([1., 2., 3., 4.])

*Cambiando el tipo de dato del array*

In [5]:
arr2 = np.array([0,1,2,3,4])

In [6]:
#Convertir arr2 a tipo flotante64 con el metodo astype
arr2.astype(np.float64)

array([0., 1., 2., 3., 4.])

*Cambiando el tipo de dato del array a booleano*

In [7]:
arr2.astype(np.bool_)

array([False,  True,  True,  True,  True])

*Cambiando el tipo de dato del array a texto*

In [8]:
arr2.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

*Cambiando el array de texto a entero*

In [9]:
arr3 = np.array(['0','1','2','3','4'])
arr3

array(['0', '1', '2', '3', '4'], dtype='<U1')

In [10]:
arr3.astype(np.int64)

array([0, 1, 2, 3, 4], dtype=int64)