In [2]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
tensor = np.array([[[12,34],[156,67],[546,768]],[[677,75],[45,76],[67,8]],[[234,2435],[567,56],[45,67]]])
print(tensor)
tensor.ndim

[[[  12   34]
  [ 156   67]
  [ 546  768]]

 [[ 677   75]
  [  45   76]
  [  67    8]]

 [[ 234 2435]
  [ 567   56]
  [  45   67]]]


3

##Agregar o eliminar dimensiones

In [7]:
n_tensor = np.array([1,2,3],ndmin=10)
print(n_tensor)
n_tensor.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [8]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [9]:
#Comprimir un vector que no esta siendo utilizado correctamente
print("Este es el vector: ",n_tensor," Numero de dimensiones: ",n_tensor.ndim)
n_tensor2 = np.squeeze(n_tensor)
print("Este es el vector: ",n_tensor2," Numero de dimensiones: ",n_tensor2.ndim)

Este es el vector:  [[[[[[[[[[1 2 3]]]]]]]]]]  Numero de dimensiones:  10
Este es el vector:  [1 2 3]  Numero de dimensiones:  1


<h1>Reto</h1>

In [24]:
tensor_5d = np.array([[[[[4],[1]],[[5],[6]]],[[[7],[1]],[[71],[15]]]],[[[[23],[11]],[[12],[41]]],[[[51],[35]],[[56],[43]]]]])
print(tensor_5d)
print(tensor_5d.ndim)
tensor_5d = np.squeeze(tensor_5d)
print(tensor_5d)
print(tensor_5d.ndim)
tensor_5d = np.expand_dims(tensor_5d,axis=1)
print(tensor_5d.ndim)
print(tensor_5d)

[[[[[ 4]
    [ 1]]

   [[ 5]
    [ 6]]]


  [[[ 7]
    [ 1]]

   [[71]
    [15]]]]



 [[[[23]
    [11]]

   [[12]
    [41]]]


  [[[51]
    [35]]

   [[56]
    [43]]]]]
5
[[[[ 4  1]
   [ 5  6]]

  [[ 7  1]
   [71 15]]]


 [[[23 11]
   [12 41]]

  [[51 35]
   [56 43]]]]
4
5
[[[[[ 4  1]
    [ 5  6]]

   [[ 7  1]
    [71 15]]]]



 [[[[23 11]
    [12 41]]

   [[51 35]
    [56 43]]]]]
