In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.linspace(5,10,100)

array([ 5.        ,  5.05050505,  5.1010101 ,  5.15151515,  5.2020202 ,
        5.25252525,  5.3030303 ,  5.35353535,  5.4040404 ,  5.45454545,
        5.50505051,  5.55555556,  5.60606061,  5.65656566,  5.70707071,
        5.75757576,  5.80808081,  5.85858586,  5.90909091,  5.95959596,
        6.01010101,  6.06060606,  6.11111111,  6.16161616,  6.21212121,
        6.26262626,  6.31313131,  6.36363636,  6.41414141,  6.46464646,
        6.51515152,  6.56565657,  6.61616162,  6.66666667,  6.71717172,
        6.76767677,  6.81818182,  6.86868687,  6.91919192,  6.96969697,
        7.02020202,  7.07070707,  7.12121212,  7.17171717,  7.22222222,
        7.27272727,  7.32323232,  7.37373737,  7.42424242,  7.47474747,
        7.52525253,  7.57575758,  7.62626263,  7.67676768,  7.72727273,
        7.77777778,  7.82828283,  7.87878788,  7.92929293,  7.97979798,
        8.03030303,  8.08080808,  8.13131313,  8.18181818,  8.23232323,
        8.28282828,  8.33333333,  8.38383838,  8.43434343,  8.48

In [8]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
np.random.rand()

0.9146039740349167

In [10]:
np.random.rand(4)

array([0.74733342, 0.0150685 , 0.182024  , 0.5769079 ])

In [11]:
np.random.rand(4,4)

array([[0.46281753, 0.97695054, 0.55645653, 0.19156545],
       [0.68890518, 0.48430549, 0.90449379, 0.20866517],
       [0.862222  , 0.91297656, 0.53101522, 0.50106188],
       [0.71982739, 0.42355272, 0.27944208, 0.56071671]])

In [12]:
np.random.randint(1,15)

5

In [13]:
np.random.randint(1,100,(10,10))

array([[35, 87, 96, 45,  8, 73, 34, 49, 20, 21],
       [15, 43, 44, 59, 24, 80,  2, 94, 24, 42],
       [84, 28, 69,  6, 38, 18, 70, 47, 49, 17],
       [37, 51, 40, 59, 29, 83, 57,  2, 91, 59],
       [72, 34, 83, 60,  9, 82, 95, 55, 71, 51],
       [68, 45, 42, 84, 84, 78, 66, 67, 37, 33],
       [93, 32, 30, 84, 41, 82, 29, 51, 51, 82],
       [42, 60, 58, 75, 11, 74, 58, 93, 73, 81],
       [49, 78, 66, 79, 57, 39, 47, 68, 76, 53],
       [43,  7, 62, 67, 12, 41, 28,  1, 60, 23]])