In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,3,3))

In [6]:
arr.shape

(3, 3, 3)

In [7]:
arr

array([[[7, 4, 6],
        [7, 7, 2],
        [9, 1, 1]],

       [[6, 3, 6],
        [2, 9, 3],
        [7, 4, 1]],

       [[2, 1, 5],
        [7, 5, 1],
        [8, 9, 1]]])

In [10]:
#Para que reshape funcione requiere que su nueva forma sea multiplo del
#Array original pj = (3,3,3) y (1,27) es lo mismo que 3x3x3 = 27 ; 1x27 = 27
arr.reshape(1,27)

array([[7, 4, 6, 7, 7, 2, 9, 1, 1, 6, 3, 6, 2, 9, 3, 7, 4, 1, 2, 1, 5, 7,
        5, 1, 8, 9, 1]])

In [11]:
arr.reshape(3,1,9)

array([[[7, 4, 6, 7, 7, 2, 9, 1, 1]],

       [[6, 3, 6, 2, 9, 3, 7, 4, 1]],

       [[2, 1, 5, 7, 5, 1, 8, 9, 1]]])

Ordenar como lenguaje C (prioriza por filas)

In [12]:
np.reshape(arr,(1,3,9),'C')

array([[[7, 4, 6, 7, 7, 2, 9, 1, 1],
        [6, 3, 6, 2, 9, 3, 7, 4, 1],
        [2, 1, 5, 7, 5, 1, 8, 9, 1]]])

Ordenar como lenguaje Fortran (prioriza por columnas)

In [13]:
np.reshape(arr,(1,3,9),'F')

array([[[7, 7, 9, 4, 7, 1, 6, 2, 1],
        [6, 2, 7, 3, 9, 4, 6, 3, 1],
        [2, 7, 8, 1, 5, 9, 5, 1, 1]]])

Ordena de acuerdo a la optimizacion del guardado de datos en mi sistema (aleatoriamente entre C o F)

In [14]:
np.reshape(arr,(1,3,9),'A')

array([[[7, 4, 6, 7, 7, 2, 9, 1, 1],
        [6, 3, 6, 2, 9, 3, 7, 4, 1],
        [2, 1, 5, 7, 5, 1, 8, 9, 1]]])