In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,3,3))

In [3]:
arr.shape

(3, 3, 3)

In [4]:
arr

array([[[7, 4, 6],
        [3, 9, 5],
        [7, 1, 8]],

       [[8, 3, 1],
        [1, 7, 1],
        [1, 9, 8]],

       [[4, 6, 4],
        [5, 8, 8],
        [6, 6, 2]]])

In [5]:
#Para que reshape funcione requiere que su nueva forma sea multiplo del
#Array original pj = (3,3,3) y (1,27) es lo mismo que 3x3x3 = 27 ; 1x27 = 27
arr.reshape(1,27)

array([[7, 4, 6, 3, 9, 5, 7, 1, 8, 8, 3, 1, 1, 7, 1, 1, 9, 8, 4, 6, 4, 5,
        8, 8, 6, 6, 2]])

In [6]:
arr.reshape(3,1,9)

array([[[7, 4, 6, 3, 9, 5, 7, 1, 8]],

       [[8, 3, 1, 1, 7, 1, 1, 9, 8]],

       [[4, 6, 4, 5, 8, 8, 6, 6, 2]]])

Ordenar como lenguaje C (prioriza por filas)

In [7]:
np.reshape(arr,(1,3,9),'C')

array([[[7, 4, 6, 3, 9, 5, 7, 1, 8],
        [8, 3, 1, 1, 7, 1, 1, 9, 8],
        [4, 6, 4, 5, 8, 8, 6, 6, 2]]])

Ordenar como lenguaje Fortran (prioriza por columnas)

In [8]:
np.reshape(arr,(1,3,9),'F')

array([[[7, 3, 7, 4, 9, 1, 6, 5, 8],
        [8, 1, 1, 3, 7, 9, 1, 1, 8],
        [4, 5, 6, 6, 8, 6, 4, 8, 2]]])

Ordena de acuerdo a la optimizacion del guardado de datos en mi sistema (aleatoriamente entre C o F)

In [9]:
np.reshape(arr,(1,3,9),'A')

array([[[7, 4, 6, 3, 9, 5, 7, 1, 8],
        [8, 3, 1, 1, 7, 1, 1, 9, 8],
        [4, 6, 4, 5, 8, 8, 6, 6, 2]]])