In [1]:
import numpy as np

In [2]:
vector = np.random.randint(1,20,(10))
vector

array([16,  4,  5, 15, 16, 17, 10, 10, 10,  5])

In [3]:
matriz = vector.reshape(2,5)
matriz

array([[16,  4,  5, 15, 16],
       [17, 10, 10, 10,  5]])

In [4]:
#Trae el numero mas grande del array
vector.max()

17

In [5]:
#Trae el numero mas grande del eje 0 (en este caso columnas)
matriz.max(0)

array([17, 10, 10, 15, 16])

In [6]:
#Trae el numero mas grande del eje 1(en este caso filas)
matriz.max(1)

array([16, 17])

In [7]:
#Trae el indice del elemento maximo, aunque haya otros iguales, trae el primero en orden
vector.argmax(0)

5

In [8]:
#Trae el indice del elemento maximo, el argumento es el indice del eje

matriz.argmax(1)

array([0, 0], dtype=int64)

EJES:
0: COLUMNAS
1: FILAS
2: PROFUNDIDAD
3: SIN NOMBRE (ELEMENTOS DE TENSORES 4D EN ADELANTE)

In [9]:
#Trae el numero mas pequeño del eje  o del total cuando arg es vacio

vector.min()

4

In [10]:
print(matriz.min())
print(matriz.min(0))
print(matriz.min(1))

4
[16  4  5 10  5]
[4 5]


In [11]:
#Trae el indice del numero mas pequeño de la matriz si no se pasa argumento(), o del eje si se pasa argumento(x)
matriz.argmin()

1

In [12]:
# Nos trae la distancia entre el minimo y el maximo del array
vector.ptp()

13

In [13]:
# Nos trae la distancia entre el minimo y el maximo de la matriz, o del eje seleccionado dentro de la matriz
matriz.ptp()

13

In [14]:
#Ordena el array de menor a mayor
vector.sort()
vector

array([ 4,  5,  5, 10, 10, 10, 15, 16, 16, 17])

In [15]:
#Retorna los percentiles 
print(np.percentile(vector,0))
print(np.percentile(vector,50))
print(np.percentile(vector,100))

4.0
10.0
17.0


In [16]:
#Retorna la mediana
print(np.median(vector))
print(np.median(matriz))
#Tambien aplica por eje
print(np.median(matriz,1))

10.0
10.0
[ 5. 16.]


In [17]:
#Retorna la desviacion estandar
print(np.std(vector))
print(np.std(matriz))
#Tambien aplica por eje
print(np.std(matriz,1))

4.749736834815167
4.749736834815167
[2.63818119 2.48193473]


In [18]:
#Retorna la varianza (std^2)
print(np.var(vector))
print(np.var(matriz))
#Tambien aplica por eje
print(np.var(matriz,1))

22.56
22.56
[6.96 6.16]


In [19]:
#Retorna el promedio
print(np.mean(vector))
print(np.mean(matriz))
#Tambien aplica por eje
print(np.mean(matriz,1))

10.8
10.8
[ 6.8 14.8]


In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [21]:
#np.concatenate((a,b),axis=0)

In [22]:
a.ndim
b.ndim

1

In [23]:
b = np.expand_dims(b,axis=0)

In [24]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
#Utilizando la transpuesta
a.T

array([[1, 3],
       [2, 4]])

In [26]:
#La transpuesta de una matriz 2x3 se convierte e una 3x2
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [27]:
#Expandir y concatenar en el otro eje (el mismo resultado que la transpuesta)
b = np.array([5,6])
b
b = np.expand_dims(b,axis=1)
b

array([[5],
       [6]])

In [28]:
b = np.concatenate((a,b),axis=1)
b


array([[1, 2, 5],
       [3, 4, 6]])