In [60]:
import numpy as np

In [61]:
vector = np.random.randint(1,20,(10))
vector

array([ 2,  1,  3,  3,  8, 17,  1,  5, 15, 12])

In [62]:
matriz = vector.reshape(2,5)
matriz

array([[ 2,  1,  3,  3,  8],
       [17,  1,  5, 15, 12]])

In [63]:
#Trae el numero mas grande del array
vector.max()

17

In [64]:
#Trae el numero mas grande del eje 0 (en este caso columnas)
matriz.max(0)

array([17,  1,  5, 15, 12])

In [65]:
#Trae el numero mas grande del eje 1(en este caso filas)
matriz.max(1)

array([ 8, 17])

In [66]:
#Trae el indice del elemento maximo, aunque haya otros iguales, trae el primero en orden
vector.argmax(0)

5

In [67]:
#Trae el indice del elemento maximo, el argumento es el indice del eje

matriz.argmax(1)

array([4, 0], dtype=int64)

EJES:
0: COLUMNAS
1: FILAS
2: PROFUNDIDAD
3: SIN NOMBRE (ELEMENTOS DE TENSORES 4D EN ADELANTE)

In [68]:
#Trae el numero mas pequeño del eje  o del total cuando arg es vacio

vector.min()

1

In [69]:
print(matriz.min())
print(matriz.min(0))
print(matriz.min(1))

1
[2 1 3 3 8]
[1 1]


In [70]:
#Trae el indice del numero mas pequeño de la matriz si no se pasa argumento(), o del eje si se pasa argumento(x)
matriz.argmin()

1

In [71]:
# Nos trae la distancia entre el minimo y el maximo del array
vector.ptp()

16

In [72]:
# Nos trae la distancia entre el minimo y el maximo de la matriz, o del eje seleccionado dentro de la matriz
matriz.ptp()

16

In [73]:
#Ordena el array de menor a mayor
vector.sort()
vector

array([ 1,  1,  2,  3,  3,  5,  8, 12, 15, 17])

In [74]:
#Retorna los percentiles 
print(np.percentile(vector,0))
print(np.percentile(vector,50))
print(np.percentile(vector,100))

1.0
4.0
17.0


In [75]:
#Retorna la mediana
print(np.median(vector))
print(np.median(matriz))
#Tambien aplica por eje
print(np.median(matriz,1))

4.0
4.0
[ 2. 12.]


In [76]:
#Retorna la desviacion estandar
print(np.std(vector))
print(np.std(matriz))
#Tambien aplica por eje
print(np.std(matriz,1))

5.675385449465085
5.675385449465085
[0.89442719 4.40908154]


In [77]:
#Retorna la varianza (std^2)
print(np.var(vector))
print(np.var(matriz))
#Tambien aplica por eje
print(np.var(matriz,1))

32.21
32.21
[ 0.8  19.44]


In [78]:
#Retorna el promedio
print(np.mean(vector))
print(np.mean(matriz))
#Tambien aplica por eje
print(np.mean(matriz,1))

6.7
6.7
[ 2.  11.4]


In [109]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [89]:
#np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [110]:
a.ndim
b.ndim

1

In [111]:
b = np.expand_dims(b,axis=0)

In [112]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [122]:
#Utilizando la transpuesta
a.T

array([[1, 3],
       [2, 4]])

In [116]:
#La transpuesta de una matriz 2x3 se convierte e una 3x2
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [102]:
#Expandir y concatenar en el otro eje (el mismo resultado que la transpuesta)
b = np.array([5,6])
b
b = np.expand_dims(b,axis=1)
b

2

In [105]:
b = np.concatenate((a,b),axis=1)
b


array([[1, 2, 5],
       [3, 4, 6]])