In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr_sliced = arr[0:6]
arr_sliced

array([0, 1, 2, 3, 4, 5])

In [10]:
arr_sliced[:] = 0
arr_sliced

array([0, 0, 0, 0, 0, 0])

In [12]:
#Khe esta pazando señor garcia, mi array original se volvio 0 tambien
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

El array sliced sigue haciendo referencia al original, por lo tanto cualquier cambio realizado ahi se reflejara en el array original.

In [14]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 100
print(arr_copy)
#El array original sigue siendo el mismo sin modificacion
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]
